openapi: "3.0.0"
info:
  version: 1.0.0
  title: Accounts
servers:
  - url: http://localhost:8080/v1
paths:
  /account:
    post:
      summary: Create account
      operationId: createAccount
      tags:
        - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAccountDTO'
      responses:
        '204':
          description: Account successfully created.
        '406':
          description: Account already exists.
components:
  schemas:
    RequestAccountDTO:
      "type": object
      required:
        - username
        - password
        - accountRoles
      properties:
        username:
          type: string
          minLength: 5
          maxLength: 10
        password:
          type: string
          minLength: 10
          maxLength: 15
        accountRoles:
          type: array
          items:
            $ref: "#/components/schemas/AccountRoles"

    AccountRoles:
      type: string
      enum:
        - USER
        - ADMIN