openapi: "3.0.0"
info:
  version: 1.0.0
  title: Accounts
servers:
  - url: http://localhost:8080/v1
paths:
  /account:
    get:
      summary: Retrieve account information
      operationId: getAccount
      tags:
        - accounts
      responses:
        200:
          description: Account information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAccountDTO'
        401:
          description: "Not authorized."
    post:
      summary: Create account
      operationId: createAccount
      tags:
        - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAccountDTO'
      responses:
        201:
          description: Account successfully created.
        400:
          description: Request malformed.
        406:
          description: Account already exists.
components:
  schemas:
    RequestAccountDTO:
      "type": object
      required:
        - username
        - password
        - accountRoles
      properties:
        username:
          $ref: "#/components/schemas/Username"
        password:
          type: string
          format: password
          minLength: 10
          maxLength: 15
    ResponseAccountDTO:
      "type": object
      required:
        - id
        - username
      properties:
        id:
          type: string
          format: uuid
        username:
          $ref: "#/components/schemas/Username"

    Username:
      type: string
      minLength: 5
      maxLength: 10