/*
 * This file was generated by the Gradle 'init' task.
 */
project.version = project.findProperty("projVersion") ?: "0.1.0-SNAPSHOT"

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.lombok)
}

dependencies {
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.jakarta.validation)
    implementation(libs.springdoc.openapi)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.spring.boot.starter.test)
    compileOnly(libs.jakarta.servlet.api)
    implementation(project(":account:webservice-contracts"))
}