services:
  postgresql:
    image: postgres:16
    pull_policy: missing
    entrypoint: [ "docker-entrypoint.sh", "--max-prepared_transactions=200" ]
    restart: always
    expose: [ "5432" ]
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/docker-entrypoint-initdb.d"
    healthcheck:
      test: pg_isready -U vault-user -d vault
    environment:
      POSTGRES_PASSWORD: "change-me"
  vault:
    image: ghcr.io/zafarius/vault:0.2.0-SNAPSHOT
    volumes:
      - data:/application/data:rw
    pull_policy: missing
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      JDBC_HOST: postgresql
      JDBC_PORT: 5432
      JDBC_DATABASE: vault
      JDBC_USERNAME: vault-user
      JDBC_PASSWORD: vaultMaster123
      JDBC_CONNECTION_POOL_MIN: 5
      JDBC_CONNECTION_POOL_MAX: 20
      FILES_OUTPUT_DIR: /application/data
    depends_on:
      - postgresql
volumes:
  data: