openapi: "3.0.0"
info:
  version: 1.0.0
  title: Files
servers:
  - url: http://localhost:8080/v1
paths:
  /account/{accountId}/file:
    get:
      summary: Request files
      operationId: getFiles
      tags:
        - files
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Requested files.
          content:
            application/zip:
              schema:
                type: string
                format: binary
        400:
          description: Request malformed.
        403:
          description: Request forbidden.
    post:
      summary: Upload files
      operationId: uploadFiles
      tags:
        - files
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - files
              properties:
                files:
                  type: array
                  minItems: 1
                  items:
                    type: string
                    format: binary
      responses:
        201:
          description: Files successfully uploaded.
        400:
          description: Request malformed.
        403:
          description: Request forbidden.