openapi: "3.0.0"
info:
  version: 1.0.0
  title: Files
servers:
  - url: http://localhost:8080/v1
paths:
  /account/{accountId}/file:
    get:
      summary: Request files
      operationId: getFiles
      tags:
        - files
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: searchRequestDTO
          required: true
          schema:
            title: searchRequestDTO
            type: object
            required:
              - pageSize
              - pageNumber
              - sortBy
            properties:
              pageSize:
                type: integer
                minimum: 1
                maximum: 5
              pageNumber:
                type: integer
                minimum: 0
                maximum: 100
              sortBy:
                type: string
                enum:
                  - CREATED_DATE
      responses:
        200:
          description: Requested files.
          content:
            application/json:
              schema:
                type: object
                title: ResponsePageVault
                required:
                  - totalPages
                  - contentSize
                  - content
                properties:
                  totalPages:
                    type: integer
                    description: Total available pages.
                  contentSize:
                    type: integer
                    description: Size of portion.
                  content:
                    type: string
                    description: Base64 encoded zipped byte code.
        400:
          description: Request malformed.
        403:
          description: Request forbidden.
        404:
          description: Requested elements not found.
    post:
      summary: Upload files
      operationId: uploadFiles
      tags:
        - files
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - files
              properties:
                files:
                  type: array
                  minItems: 1
                  items:
                    type: string
                    format: binary
      responses:
        201:
          description: Files successfully uploaded.
        400:
          description: Request malformed.
        403:
          description: Request forbidden.