/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.lombok)
}

dependencies {
    api(libs.spring.boot.starter.security)
    implementation(project(":account:repository"))
}