/*
 * This source file was generated by the Gradle 'init' task
 */
package vault;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class VaultApplication {
    public static void main(final String[] args) {
        SpringApplication.run(VaultApplication.class, args);
    }
}
