server:
  port: 8080

spring:
  session:
    timeout: 10m
  h2:
    console:
      enabled: false
  jta:
    atomikos:
      datasource:
        min-pool-size: ${JDBC_CONNECTION_POOL_MIN}
        max-pool-size: ${JDBC_CONNECTION_POOL_MAX}
      properties:
        enable-logging: false
        log-base-name: VAULT_XA
        log-base-dir: /application/data/jta

    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.connection.charSet: UTF-8
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.generate_statistics: true
      hibernate.id.new_generator_mappings: true
      hibernate.globally_quoted_identifiers: true
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
  datasource:
    url: jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DATABASE}?reWriteBatchedInserts=true
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
logging:
  level:
    vault: WARN
    com:
      atomikos: ERROR
files:
  output_dir: ${FILES_OUTPUT_DIR}